version: '2'
services:
  clair-postgres:
    container_name: clair-postgres
    image: postgres:latest
    restart: always
    networks:
      - adop-network
    environment:
      POSTGRES_PASSWORD: password
    
  adop-clair:
    container_name: adop-clair
    image: dockerhub.accenture.com/john.arcy.r.teodoro/adop-clair:0.1
    restart: always
    networks:
      - adop-network
    depends_on:
      - clair-postgres
    expose:
      - "6060-6061"
    environment:
      - "POSTGRES_URL=${POSTGRES_URL}"
    command: [-config, /config/config.yaml]

networks:
  adop-network:
    external: true